language: ruby
rvm:
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"
  - "jruby-9.1.9.0"
  - "jruby-head"
script:
  bundle exec rake test

sudo: false
cache: bundler

before_install:
  # get latest rubygems due to weird bugs
  - gem update --system
  - gem install bundler

env:
  # avoid jruby unknown property jruby.cext.enabled
  # https://github.com/travis-ci/travis-ci/issues/6471
  - JRUBY_OPTS=''
